<?php
namespace App\Api;
use PhalApi\Api;

class Callback extends Api
{
    public function getRules() {
        return parent::getRules(); // TODO: Change the autogenerated stub
    }

    public function Unlock()
    {

    }
}