<?php
namespace App\Api;
use PhalApi\Api;

/**
 * 设备管理类
 * @package App\Api
 */
class Device extends Api
{
    public function getRules() {
        return parent::getRules(); // TODO: Change the autogenerated stub
    }

    /**
     * 查看设备在线状态
     * @desc 查看某设备的在线状态
     * @ignore
     */
    public function Status()
    {

    }
}